async function req(path, options = {}) {
  const res = await fetch(path, {
    headers: { 'Content-Type': 'application/json' },
    credentials: 'include',
    ...options,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(data.error || `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  return data;
}

export const api = {
  me: () => req('/api/auth/me'),
  login: (identifier, password) => req('/api/auth/login', { method: 'POST', body: JSON.stringify({ identifier, password }) }),
  register: (username, email, password) => req('/api/auth/register', { method: 'POST', body: JSON.stringify({ username, email, password }) }),
  logout: () => req('/api/auth/logout', { method: 'POST' }),
  userSearch: (q) => req(`/api/users/search?q=${encodeURIComponent(q)}`),
  activity: (id) => req(`/api/client/servers/${id}/activity`),

  // ── Client area ──────────────────────────────────────────
  servers: () => req('/api/client/servers'),
  server: (id) => req(`/api/client/servers/${id}`),
  power: (id, action) => req(`/api/client/servers/${id}/power`, { method: 'POST', body: JSON.stringify({ action }) }),
  command: (id, command) => req(`/api/client/servers/${id}/command`, { method: 'POST', body: JSON.stringify({ command }) }),
  console: (id) => req(`/api/client/servers/${id}/console`),
  files: (id, path) => req(`/api/client/servers/${id}/files?path=${encodeURIComponent(path)}`),
  readFile: (id, path) => req(`/api/client/servers/${id}/files/read`, { method: 'POST', body: JSON.stringify({ path }) }),
  writeFile: (id, path, content) => req(`/api/client/servers/${id}/files/write`, { method: 'POST', body: JSON.stringify({ path, content }) }),
  deleteFile: (id, path) => req(`/api/client/servers/${id}/files/delete`, { method: 'POST', body: JSON.stringify({ path }) }),
  renameFile: (id, path, newPath) => req(`/api/client/servers/${id}/files/rename`, { method: 'POST', body: JSON.stringify({ path, newPath }) }),
  resources: (id) => req(`/api/client/servers/${id}/resources`),
  installLog: (id) => req(`/api/client/servers/${id}/install-log`),
  databases: (id) => req(`/api/client/servers/${id}/databases`),
  createDatabase: (id, name) => req(`/api/client/servers/${id}/databases`, { method: 'POST', body: JSON.stringify({ name }) }),
  deleteDatabase: (dbId) => req(`/api/client/databases/${dbId}`, { method: 'DELETE' }),
  rotateDatabase: (dbId) => req(`/api/client/databases/${dbId}/rotate`, { method: 'POST' }),
  startup: (id) => req(`/api/client/servers/${id}/startup`),
  updateStartup: (id, env) => req(`/api/client/servers/${id}/startup`, { method: 'PATCH', body: JSON.stringify({ env }) }),
  updateSettings: (id, body) => req(`/api/client/servers/${id}/settings`, { method: 'PATCH', body: JSON.stringify(body) }),
  reinstall: (id) => req(`/api/client/servers/${id}/reinstall`, { method: 'POST' }),
  schedules: (id) => req(`/api/client/servers/${id}/schedules`),
  createSchedule: (id, body) => req(`/api/client/servers/${id}/schedules`, { method: 'POST', body: JSON.stringify(body) }),
  updateSchedule: (id, body) => req(`/api/client/schedules/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  deleteSchedule: (id) => req(`/api/client/schedules/${id}`, { method: 'DELETE' }),
  createScheduleTask: (id, body) => req(`/api/client/schedules/${id}/tasks`, { method: 'POST', body: JSON.stringify(body) }),
  deleteScheduleTask: (id) => req(`/api/client/schedule-tasks/${id}`, { method: 'DELETE' }),
  subusers: (id) => req(`/api/client/servers/${id}/users`),
  createSubuser: (id, body) => req(`/api/client/servers/${id}/users`, { method: 'POST', body: JSON.stringify(body) }),
  updateSubuser: (id, body) => req(`/api/client/subusers/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  deleteSubuser: (id) => req(`/api/client/subusers/${id}`, { method: 'DELETE' }),
  backups: (id) => req(`/api/client/servers/${id}/backups`),
  createBackup: (id, name) => req(`/api/client/servers/${id}/backups`, { method: 'POST', body: JSON.stringify({ name }) }),
  downloadBackup: (id) => req(`/api/client/backups/${id}/download`),
  restoreBackup: (id) => req(`/api/client/backups/${id}/restore`, { method: 'POST' }),
  deleteBackup: (id) => req(`/api/client/backups/${id}`, { method: 'DELETE' }),
  network: (id) => req(`/api/client/servers/${id}/network`),
  sftp: (id) => req(`/api/client/servers/${id}/sftp`),
  rotateSftp: (id) => req(`/api/client/servers/${id}/sftp/password`, { method: 'POST' }),

  // ── Admin ────────────────────────────────────────────────
  admin: {
    overview: () => req('/api/admin/overview'),
    settings: () => req('/api/admin/settings'),
    updateSettings: (body) => req('/api/admin/settings', { method: 'PATCH', body: JSON.stringify(body) }),
    apiKeys: () => req('/api/admin/api-keys'),
    createApiKey: (description, permissions) => req('/api/admin/api-keys', { method: 'POST', body: JSON.stringify({ description, permissions }) }),
    deleteApiKey: (id) => req(`/api/admin/api-keys/${id}`, { method: 'DELETE' }),
    locations: () => req('/api/admin/locations'),
    createLocation: (short, long) => req('/api/admin/locations', { method: 'POST', body: JSON.stringify({ short, long }) }),
    updateLocation: (id, body) => req(`/api/admin/locations/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteLocation: (id) => req(`/api/admin/locations/${id}`, { method: 'DELETE' }),
    nodes: () => req('/api/admin/nodes'),
    createNode: (body) => req('/api/admin/nodes', { method: 'POST', body: JSON.stringify(body) }),
    updateNode: (id, body) => req(`/api/admin/nodes/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteNode: (id) => req(`/api/admin/nodes/${id}`, { method: 'DELETE' }),
    nodeAllocations: (id) => req(`/api/admin/nodes/${id}/allocations`),
    addAllocation: (id, ip, port) => req(`/api/admin/nodes/${id}/allocations`, { method: 'POST', body: JSON.stringify({ ip, port }) }),
    addAllocationRange: (id, ip, from, to) => req(`/api/admin/nodes/${id}/allocations/range`, { method: 'POST', body: JSON.stringify({ ip, from, to }) }),
    deleteAllocation: (id) => req(`/api/admin/allocations/${id}`, { method: 'DELETE' }),
    users: () => req('/api/admin/users'),
    createUser: (body) => req('/api/admin/users', { method: 'POST', body: JSON.stringify(body) }),
    updateUser: (id, body) => req(`/api/admin/users/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteUser: (id) => req(`/api/admin/users/${id}`, { method: 'DELETE' }),
    servers: (search) => req(`/api/admin/servers${search ? `?search=${encodeURIComponent(search)}` : ''}`),
    server: (id) => req(`/api/admin/servers/${id}`),
    createServer: (body) => req('/api/admin/servers', { method: 'POST', body: JSON.stringify(body) }),
    assignServer: (id, userId) => req(`/api/admin/servers/${id}/assign`, { method: 'PATCH', body: JSON.stringify({ user_id: userId }) }),
    updateServer: (id, body) => req(`/api/admin/servers/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteServer: (id) => req(`/api/admin/servers/${id}`, { method: 'DELETE' }),
    serverPower: (id, action) => req(`/api/admin/servers/${id}/power`, { method: 'POST', body: JSON.stringify({ action }) }),
    suspendServer: (id) => req(`/api/admin/servers/${id}/suspend`, { method: 'POST' }),
    unsuspendServer: (id) => req(`/api/admin/servers/${id}/unsuspend`, { method: 'POST' }),
    reinstallServer: (id) => req(`/api/admin/servers/${id}/reinstall`, { method: 'POST' }),
    nests: () => req('/api/admin/nests'),
    createNest: (name, description) => req('/api/admin/nests', { method: 'POST', body: JSON.stringify({ name, description }) }),
    deleteNest: (id) => req(`/api/admin/nests/${id}`, { method: 'DELETE' }),
    eggs: (nestId) => req(`/api/admin/nests/${nestId}/eggs`),
    egg: (id) => req(`/api/admin/eggs/${id}`),
    createEgg: (nestId, body) => req(`/api/admin/nests/${nestId}/eggs`, { method: 'POST', body: JSON.stringify(body) }),
    updateEgg: (id, body) => req(`/api/admin/eggs/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteEgg: (id) => req(`/api/admin/eggs/${id}`, { method: 'DELETE' }),
    createEggVariable: (eggId, body) => req(`/api/admin/eggs/${eggId}/variables`, { method: 'POST', body: JSON.stringify(body) }),
    updateEggVariable: (id, body) => req(`/api/admin/egg-variables/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteEggVariable: (id) => req(`/api/admin/egg-variables/${id}`, { method: 'DELETE' }),
    databases: () => req('/api/admin/databases'),
    createServerDatabase: (serverId, name) => req(`/api/admin/servers/${serverId}/databases`, { method: 'POST', body: JSON.stringify({ name }) }),
    deleteDatabase: (id) => req(`/api/admin/databases/${id}`, { method: 'DELETE' }),
    rotateDatabase: (id) => req(`/api/admin/databases/${id}/rotate`, { method: 'POST' }),
    mounts: () => req('/api/admin/mounts'),
    createMount: (body) => req('/api/admin/mounts', { method: 'POST', body: JSON.stringify(body) }),
    updateMount: (id, body) => req(`/api/admin/mounts/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
    deleteMount: (id) => req(`/api/admin/mounts/${id}`, { method: 'DELETE' }),
  },
};
